### ISSUE TITLE
The VM resource contains a fixed macAddress

### ISSUE THREAD

**Issue by iocanel** [iocanel/openshift-vm-playground#11]
This means that we are prone to mac address clashing. For example:

- We can't install the same VM in another namespace in the same cluster.
- It's possible that we can't install the same definition in another cluster.

Unfortunately, removing the `macAddress` property in the network interface cause the VM to stuck in `Starting` state. We need to find a better solution.

**Comment by cmoulliard** [comment]
I agree with you that we need either a mechanism able to generate such a macaddress to avoid to hard code them with the YAML resource
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
...
          interfaces:
            - macAddress: '02:38:72:00:00:18'
              masquerade: {}
              model: virtio
              name: default
```

**Comment by cmoulliard** [comment]
As we can set ourself the mac address (to be confirmed), then we could generate it:
`od -An -N6 -tx1 /dev/urandom | sed -e 's/^  *//' -e 's/  */:/g' -e 's/:$//' -e 's/^\(.\)[13579bdf]/\10/'` 

see: https://stackoverflow.com/questions/42660218/bash-generate-random-mac-address-unicast

**Comment by cmoulliard** [comment]
macaddress is generated if not specified
```
          interfaces:
            - masquerade: {}
              # macAddress: '02:38:72:00:00:09'
              model: virtio
              name: default
```
