### ISSUE TITLE
The test pipeline should also perform deployment

### ISSUE THREAD

**Issue by iocanel** [iocanel/openshift-vm-playground#15]
The pipeline currently performs a simple maven build.
It would be create if we had a deployment step.

The deployment step could just use `./mvnw quarkus:deploy -Dquarkus.openshift.deploy=true` or something like this.

**Comment by cmoulliard** [comment]
> The deployment step could just use `./mvnw quarkus:deploy -Dquarkus.openshift.deploy=true` or something like this.

So it will be needed that we set different values such as:
- namespace where deployment should take place
- registry where image will be pushed
- creds to push to the remote registry

**NOTE**: Pod created could fail if the backend system required (postgresql, etc) is not available. So do we plan to also manage the `binding` and/or binding + deployment of the backend ? @iocanel

**Comment by cmoulliard** [comment]
I don t see a deployment yaml created within the namespace running the tekton task "deploy". Log just reports
```
[maven-deploy : mvn-goals] [INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 696ms
[maven-deploy : mvn-goals] [INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Selecting target 'openshift' since it has the highest priority among the implicitly enabled deployment targets
[maven-deploy : mvn-goals] [INFO] [io.quarkus.kubernetes.deployment.PropertyUtil] Openshift manifests are generated with 'The container port http' having default value '8080'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
[maven-deploy : mvn-goals] [INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 4084ms
[maven-deploy : mvn-goals] [INFO] ------------------------------------------------------------------------
```

**Comment by cmoulliard** [comment]
Question: As `quarkus.openshift.deploy=true` generates ocp resources like `buildconfig.build.openshift.io`. Should we in a next step launch the build if the deployment was successfull ? @iocanel

**Comment by cmoulliard** [comment]
FYI. If we trigger a build - https://console-openshift-console.apps.qshift.snowdrop.dev/k8s/ns/test2/builds/quarkus-helloworld-1 the resulting image build fails to start from the pod
![Screenshot 2023-11-22 at 17 49 58](https://github.com/iocanel/openshift-vm-playground/assets/463790/9751209c-e0d3-4c31-8c45-1aaa868f94de)

**Comment by cmoulliard** [comment]
Build issue fixed after I changed the maven parameters to perform the build using docker and not s2i
```
    - name: maven-build
      runAfter:
        - virtualmachine
      taskRef:
        name: maven
      params:
        - name: DOCKER_HOST
          value: "tcp://$(tasks.virtualmachine.results.ip):2376"
        - name: GOALS
          value:
          - package
          - -Dquarkus.openshift.build-strategy=docker
          - -Dquarkus.container-image.build=true
          - -Dquarkus.container-image.push=true
```
