### ISSUE TITLE
Bypass docker limit issue using config.json file as DOCKER_CONFIG env for the testcontainers

### ISSUE THREAD

**Issue by cmoulliard** [iocanel/openshift-vm-playground#29]
## Issue

As users will suffer from the Docker limit, then we should pass an env var to let testcontainer to load the credentials to be authenticated with the docker.io registry

See: https://java.testcontainers.org/supported_docker_environment/#docker-registry-authentication

Something like this should work
```
  - name: maven-test
    params:
    - name: DOCKER_AUTH_CONFIG
      value: $(workspaces.dockerconfig.path)/config.json
    - name: DOCKER_HOST
      value: tcp://$(tasks.virtualmachine.results.ip):2376
    - name: GOALS
      value:
      - -B
      - test
```
