### ISSUE TITLE
Tekton substitution do not take place for DOCKER_HOST

### ISSUE THREAD

**Issue by cmoulliard** [iocanel/openshift-vm-playground#3]
## Issue

Substitution do not take place and then maven set as parameter the DOCKER_HOST like this `tcp://$(tasks.virtualmachine.results.ip):2376`

Code where results is defined
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven-run
spec:
  taskRef:
    name: maven
  params:
    - name: DOCKER_HOST
      value: tcp://$(tasks.virtualmachine.results.ip):2376
...
```
Task code exporting the result: https://github.com/iocanel/openshift-vm-playground/blob/main/pipelines/tasks/virtualmachine.yaml#L27 
TaskRun consuming the result: https://github.com/iocanel/openshift-vm-playground/blob/main/pipelines/taskruns/maven-run.yaml#L10

**NOTE**: To be investigated of course. It could be related to the fact that we cannot share results between tasks BUT instead using Pipeline + tasks ...
