### ISSUE TITLE
Tekton stratetegy to build the image: jib vs quarkus container build vs buildpacks

### ISSUE THREAD

**Issue by cmoulliard** [iocanel/openshift-vm-playground#31]
## Discussion

What should be the strategy that we will adopt/support in our pipelines to build the container image: 

Buildah task example
```
    - name: buildah
      runAfter:
        - maven-compile
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: IMAGE
          value: quay.io/ch007m/quarkus-dev-vm
      workspaces:
        - name: source
          workspace: project-dir
        - name: dockerconfig
          workspace: dockerconfig-ws
```

quarkus container JIB build example (if you set the quarkus-container-jib-extension to the pom.xml)
```         
    - name: maven-generate-deploy
      runAfter:
        - buildah
      params:
        - name: DOCKER_CONFIG
          value: $(workspaces.dockerconfig.path)/config.json
        - name: GOALS
          value:
            - package
            - '-DskipTests'
            - -B
            - -Dquarkus.container-image.image=quay.io/ch007m/quarkus-helloworld:latest
            - -Dquarkus.kubernetes.deploy=true
            - -Dquarkus.log.level=DEBUG
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: project-dir
          workspace: project-dir
        - name: maven-m2-repo
          workspace: maven-m2-repo
        - name: dockerconfig
          workspace: dockerconfig-ws
```
