### ISSUE TITLE
The VM should have a name that describes its role

### ISSUE THREAD

**Issue by iocanel** [iocanel/openshift-vm-playground#8]
Currently we are using `fedora` as the name of the VM, which describes the OS rather than the role of the VM.
So, all related resources called fedora, should be renamed to `podman-remote` etc.

**Comment by cmoulliard** [comment]
Correct me if I'm wrong but the only resource that we are creating to install a KubeVirt VM is this one 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora38
  labels:
    app: fedora38
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.25.0
```

I suggest that we name the resource as you suggest but we also include as label the underlying OS or image used to figure out when issues will take place which OS/image we are using
-->
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: podman-remote
  labels:
    app: podman-remote
    vm-os: fedora38
    vm-image: quay.io/containerdisks/fedora:38
...
```
**Warning**: Be aware that if do that it will not be possible to create x VMS within the same namespace

@iocanel
